DROP TABLE BOOK;
DROP TABLE PARAMS;

CREATE TABLE BOOK (
  BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
  BOOK_NAME VARCHAR(128) UNIQUE KEY NOT NULL,
  SALES_VOLUME INT NOT NULL DEFAULT 0,
  CREATE_TIME DATETIME,
  MODIFY_TIME DATETIME
);

CREATE TABLE PARAMS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  VALUE VARCHAR(256),
  CREATE_TIME DATETIME,
  MODIFY_TIME DATETIME
);

INSERT INTO PARAMS (NAME, VALUE, CREATE_TIME) VALUES ('sale_available', 'Y', NOW());
